### ISSUE TITLE
How return localization to System language

### ISSUE THREAD

**Issue by sglushchenko** [amosavian/LocaleManager#2]
Hello

How I can get system language after changing language?
For now, If I change language without restart the app, I can get system language with Bundle.main.preferredLocalizations.first

But if I restart application then Bundle.main.preferredLocalizations.first return changed language and I can't detect current System language

**Comment by amosavian** [comment]
Please read readme 
https://github.com/amosavian/LocaleManager#get-active-locale

**Comment by sglushchenko** [comment]
Thanks for the response
But I would like take a current system language. not the app language.
I try to apply nil locale because in your code it remove AppleLanguages, but it set to english language(my system language is Germany). Maybe it a bug of OS?

**Comment by amosavian** [comment]
aha. I didn't get the question.

I didn't swizzle anything here. Apple says this method returns localizations in your bundle. I think your app's development language is English. Maybe you mean this one:

```swift
Locale.current.languageCode
```

**Comment by sglushchenko** [comment]
I think after removeLocale application jump to Base language and my Base language is English. But I'm not sure. Ok. I will try to find a solution

**Comment by amosavian** [comment]
Maybe you should set localization to `Locale.current` in case you want to get back to system localization.

**Comment by sglushchenko** [comment]
No. System show that current locale is changed locale :)
