### ISSUE TITLE
App flips but language doesn't

### ISSUE THREAD

**Issue by talaqil** [amosavian/LocaleManager#3]
Hello there

I faced an issue in my app a problem where there is no translation from English to Arabic. Howeve, flipping works 100% fine.

I don't have storyboard, I build my UI in code.

i use the following in the AppDelegate

`        LocaleManager.setup()
          LocaleManager.rootViewController = {
            (self.window?.rootViewController)!
        }
`

and for changing the app language I use either
   LocaleManager.apply(identifier: "ar") or  LocaleManager.apply(identifier: "en")

I use NSLocalizedString(text, comment) method with localizable.strings file having arabic and english

Swit 4
LocaleManager 1.3.0

**Comment by amosavian** [comment]
You must return a new instance from the closure, not returning already initialized viewcontroller.

**Comment by talaqil** [comment]
it is done
thanks dude
